language: ruby


rvm:
  - 2.0.0

notifications:
  email:
    recepients:
      - baramik1989@gmail.com
    on_success: change
    on_failure: change
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database Amazon_test' -U postgres

# uncomment this line if your project needs to run something other than `rake`:

