language: ruby


rvm:
  - 2.0.0

notifications:
  email:
    recepients:
      - baramik1989@gmail.com
    on_success: change
    on_failure: change

before_script:
     - psql -c "CREATE DATABASE Amazon_development;" -U postgres


