language: ruby


rvm:
  - 2.0.0

notifications:
  email:
    recepients:
      - baramik1989@gmail.com
    on_success: change
    on_failure: change

script: bundle exec rspec spec
before_script:
     - psql -c 'CREATE USER Apple WITH PASSWORD 'baramik'' -U postgres
     - psql -c 'ALTER ROLE Apple SUPERUSER' -U postgres
     - psql -c 'create database Amazon_test' -U postgres

