development:
    adapter: postgresql
    encoding: unicode
    database: Amazon_development
    pool: 5
    username: Apple
    password:

test:
  adapter: postgresql
  encoding: unicode
  database: Amazon_test
  pool: 5
  username: Apple
  password: baramik

production:
  adapter: postgresql
  encoding: unicode
  database: Amazon_production
  pool: 5
  username: Apple
  password: baramik



