require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RaitingsController do

  # This should return the minimal set of attributes required to create a valid
  # Raiting. As you add validations to Raiting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RaitingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all raitings as @raitings" do
      raiting = Raiting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:raitings).should eq([raiting])
    end
  end

  describe "GET show" do
    it "assigns the requested raiting as @raiting" do
      raiting = Raiting.create! valid_attributes
      get :show, {:id => raiting.to_param}, valid_session
      assigns(:raiting).should eq(raiting)
    end
  end

  describe "GET new" do
    it "assigns a new raiting as @raiting" do
      get :new, {}, valid_session
      assigns(:raiting).should be_a_new(Raiting)
    end
  end

  describe "GET edit" do
    it "assigns the requested raiting as @raiting" do
      raiting = Raiting.create! valid_attributes
      get :edit, {:id => raiting.to_param}, valid_session
      assigns(:raiting).should eq(raiting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Raiting" do
        expect {
          post :create, {:raiting => valid_attributes}, valid_session
        }.to change(Raiting, :count).by(1)
      end

      it "assigns a newly created raiting as @raiting" do
        post :create, {:raiting => valid_attributes}, valid_session
        assigns(:raiting).should be_a(Raiting)
        assigns(:raiting).should be_persisted
      end

      it "redirects to the created raiting" do
        post :create, {:raiting => valid_attributes}, valid_session
        response.should redirect_to(Raiting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raiting as @raiting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raiting.any_instance.stub(:save).and_return(false)
        post :create, {:raiting => {  }}, valid_session
        assigns(:raiting).should be_a_new(Raiting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raiting.any_instance.stub(:save).and_return(false)
        post :create, {:raiting => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raiting" do
        raiting = Raiting.create! valid_attributes
        # Assuming there are no other raitings in the database, this
        # specifies that the Raiting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Raiting.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => raiting.to_param, :raiting => { "these" => "params" }}, valid_session
      end

      it "assigns the requested raiting as @raiting" do
        raiting = Raiting.create! valid_attributes
        put :update, {:id => raiting.to_param, :raiting => valid_attributes}, valid_session
        assigns(:raiting).should eq(raiting)
      end

      it "redirects to the raiting" do
        raiting = Raiting.create! valid_attributes
        put :update, {:id => raiting.to_param, :raiting => valid_attributes}, valid_session
        response.should redirect_to(raiting)
      end
    end

    describe "with invalid params" do
      it "assigns the raiting as @raiting" do
        raiting = Raiting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raiting.any_instance.stub(:save).and_return(false)
        put :update, {:id => raiting.to_param, :raiting => {  }}, valid_session
        assigns(:raiting).should eq(raiting)
      end

      it "re-renders the 'edit' template" do
        raiting = Raiting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raiting.any_instance.stub(:save).and_return(false)
        put :update, {:id => raiting.to_param, :raiting => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raiting" do
      raiting = Raiting.create! valid_attributes
      expect {
        delete :destroy, {:id => raiting.to_param}, valid_session
      }.to change(Raiting, :count).by(-1)
    end

    it "redirects to the raitings list" do
      raiting = Raiting.create! valid_attributes
      delete :destroy, {:id => raiting.to_param}, valid_session
      response.should redirect_to(raitings_url)
    end
  end

end
